[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
superteam_bootcamp = "2w9CcfuCJAY3ZmA2SG5WeN2V6T3zHHZppwoxPqcEp4G3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

